version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: expense_tracker_db
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - '${PGPORT}:5432'